version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:3000"
    env_file:
      - .env
    depends_on:
       - mysqldb
    profiles:
      - "product"

  mysqldb:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      SERVICE_TAGS: product
      SERVICE_NAME: mysqldb
    volumes:
      - ./db-data:/var/lib/mysql
    profiles:
      - "product"


volumes:
  mysql-data:
